version: "3.9"

services:
  services:
        api:
            container_name: api
            build:
            context: .
            dockerfile: Dockerfile
            ports:
            - "5000:5000"
            env_file:
            - .env
            restart: unless-stopped

  db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
